import {
  UOM,
  Commodity,
  Location,
  CounterParty,
  Blend,
  BlendComponent,
  Capacity,
} from "./types";

// Dummy UOMs
export const dummyUOMs: UOM[] = [
  {
    id: 1,
    name: "Kilogram",
    description: "Standard unit of mass",
    type: "Mass",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Liter",
    description: "Standard unit of volume",
    type: "Volume",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Barrel",
    description: "Oil barrel (42 US gallons)",
    type: "Volume",
    base_uom: 2,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Metric Ton",
    description: "1000 kilograms",
    type: "Mass",
    base_uom: 1,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Gallon",
    description: "US Gallon",
    type: "Volume",
    base_uom: 2,
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

// Dummy Commodities
export const dummyCommodities: Commodity[] = [
  {
    id: 1,
    name: "Crude Oil",
    description: "Brent Crude Oil",
    uom_id: 3,
    density: 0.85,
    energy_uom: "BTU",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 3, name: "Barrel" },
  },
  {
    id: 2,
    name: "Natural Gas",
    description: "Henry Hub Natural Gas",
    uom_id: 2,
    density: 0.72,
    energy_uom: "MMBtu",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 2, name: "Liter" },
  },
  {
    id: 3,
    name: "Diesel",
    description: "Ultra Low Sulfur Diesel",
    uom_id: 3,
    density: 0.832,
    energy_uom: "BTU",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 3, name: "Barrel" },
  },
  {
    id: 4,
    name: "Gasoline",
    description: "Regular Unleaded Gasoline",
    uom_id: 3,
    density: 0.755,
    energy_uom: "BTU",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 3, name: "Barrel" },
  },
  {
    id: 5,
    name: "Ethanol",
    description: "Fuel Grade Ethanol",
    uom_id: 2,
    density: 0.789,
    energy_uom: "BTU",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 2, name: "Liter" },
  },
  {
    id: 6,
    name: "Jet Fuel",
    description: "Aviation Turbine Fuel",
    uom_id: 3,
    density: 0.804,
    energy_uom: "BTU",
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
    uom: { id: 3, name: "Barrel" },
  },
];

// Dummy Counter Parties
export const dummyCounterParties: CounterParty[] = [
  {
    id: 1,
    name: "ExxonMobil",
    type: "Supplier",
    contact_info: "contact@exxonmobil.com",
    credit_status: "Approved",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Chevron",
    type: "Supplier",
    contact_info: "info@chevron.com",
    credit_status: "Approved",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Shell Trading",
    type: "Trader",
    contact_info: "trading@shell.com",
    credit_status: "Pending",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "BP America",
    type: "Customer",
    contact_info: "sales@bp.com",
    credit_status: "Approved",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Marathon Petroleum",
    type: "Customer",
    contact_info: "info@marathon.com",
    credit_status: "Rejected",
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

// Dummy Locations
export const dummyLocations: Location[] = [
  {
    id: 1,
    name: "Houston Terminal",
    location_type: "Terminal",
    address: "1234 Energy Blvd, Houston, TX 77001",
    counterparty_id: 1,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Gulf Coast Refinery",
    location_type: "Refinery",
    address: "5678 Refinery Rd, Texas City, TX 77590",
    counterparty_id: 2,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Chicago Storage",
    location_type: "Storage",
    address: "910 Industrial Way, Chicago, IL 60601",
    counterparty_id: 3,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "New Jersey Port",
    location_type: "Port",
    address: "111 Harbor Dr, Newark, NJ 07102",
    counterparty_id: 4,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Los Angeles Depot",
    location_type: "Depot",
    address: "222 Commerce St, Los Angeles, CA 90001",
    counterparty_id: 1,
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

// Dummy Blends
export const dummyBlends: Blend[] = [
  {
    id: 1,
    name: "Premium Gasoline Blend",
    commodity_id: 4,
    description: "High octane gasoline blend with ethanol",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Winter Diesel Blend",
    commodity_id: 3,
    description: "Cold weather diesel with additives",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "E85 Flex Fuel",
    commodity_id: 5,
    description: "85% Ethanol, 15% Gasoline blend",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Marine Fuel Blend",
    commodity_id: 3,
    description: "Low sulfur marine diesel",
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

// Dummy Blend Components
export const dummyBlendComponents: BlendComponent[] = [
  {
    id: 1,
    blend_id: 1,
    component_commodity_id: 4,
    percentage: 90,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[3],
    blend: dummyBlends[0],
  },
  {
    id: 2,
    blend_id: 1,
    component_commodity_id: 5,
    percentage: 10,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[4],
    blend: dummyBlends[0],
  },
  {
    id: 3,
    blend_id: 2,
    component_commodity_id: 3,
    percentage: 95,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[2],
    blend: dummyBlends[1],
  },
  {
    id: 4,
    blend_id: 2,
    component_commodity_id: 5,
    percentage: 5,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[4],
    blend: dummyBlends[1],
  },
  {
    id: 5,
    blend_id: 3,
    component_commodity_id: 5,
    percentage: 85,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[4],
    blend: dummyBlends[2],
  },
  {
    id: 6,
    blend_id: 3,
    component_commodity_id: 4,
    percentage: 15,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[3],
    blend: dummyBlends[2],
  },
];

// Dummy Capacity
export const dummyCapacity: Capacity[] = [
  {
    id: 1,
    commodity_id: 1,
    location_id: 1,
    capacity_type: "Storage",
    quantity: 500000,
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[0],
    location: dummyLocations[0],
  },
  {
    id: 2,
    commodity_id: 2,
    location_id: 2,
    capacity_type: "Processing",
    quantity: 250000,
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[1],
    location: dummyLocations[1],
  },
  {
    id: 3,
    commodity_id: 3,
    location_id: 3,
    capacity_type: "Storage",
    quantity: 100000,
    start_date: "2024-01-01",
    end_date: "2024-06-30",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[2],
    location: dummyLocations[2],
  },
  {
    id: 4,
    commodity_id: 4,
    location_id: 4,
    capacity_type: "Transport",
    quantity: 75000,
    start_date: "2024-03-01",
    end_date: "2024-09-30",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[3],
    location: dummyLocations[3],
  },
  {
    id: 5,
    commodity_id: 5,
    location_id: 5,
    capacity_type: "Storage",
    quantity: 50000,
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    is_active: false,
    created_at: "2024-01-01T00:00:00Z",
    commodity: dummyCommodities[4],
    location: dummyLocations[4],
  },
];
